### ISSUE TITLE
[BUG] Could not found 'read_dtc_info' in 'uds'

### ISSUE THREAD

**Issue by Daniboum** [rnd-ash/OpenVehicleDiag#33]
While compiling I'm getting following error:

error[E0433]: failed to resolve: could not find `read_dtc_info` in `uds`
   --> src\commapi\protocols\mod.rs:225:34
       |
225 |             Self::UDS(s) => uds::read_dtc_info::read_dtc_information(s, dtc)
       |                                              ^^^^^^^^^^^^^ could not find `read_dtc_info` in `uds`

Since the update after the Youtube Livestream from 08.07.2021, I've pulled both updated files but I'm not able to compile anymore. Unfortunately I couldn't find the solution myself but I'm pretty sure, I'll verry quickly find the problem...

**Comment by rnd-ash** [comment]
Turns out I forgot to add some changes I did to UDS/mod.rs. This should be fixed now in 6ac91874597594cef8b80616eba497f93d2838c2
